import "server-only";

import { cookies, headers } from "next/headers";
import { isbot } from "isbot";
import { analyticsTable, type AnalyticsEventRow } from "@/lib/analytics/db";
import {
  OPTOUT_COOKIE,
  SESSION_COOKIE,
  UUID_RE,
  VISITOR_COOKIE,
} from "@/lib/analytics/identity";
import { deviceTypeFrom, normalizeSearchTerm, scrubPII } from "@/lib/analytics/text";

/**
 * Server-side `search` logging.
 *
 * The client never sends this event. Only the server knows result_count and
 * result_ids, and a client-sent count can be forged — which would corrupt the
 * zero-result rate, the single most actionable number this system produces.
 *
 * Called from the catalog page after the query returns. Three things are
 * load-bearing:
 *
 *   1. The same bot and prefetch guard runs here as on /api/events. A crawler
 *      walking /catalog?q= URLs would otherwise invent demand no human ever
 *      expressed — and unlike a beacon, this path IS reachable by a crawler,
 *      so the guard matters more here than there.
 *   2. Nothing is awaited on the render path and nothing may throw. Analytics
 *      must never be able to fail a product request.
 *   3. Both scrubPII and normalizeSearchTerm run before the write, in that
 *      order, so query_norm derives from the scrubbed value.
 */
export type SearchLogInput = {
  /** Generated by the caller so it can be handed to the client for attribution. */
  id: string;
  query: string;
  resultCount: number;
  /** First 20 ids in rank order — these become impressions. */
  resultIds: string[];
  locale?: string;
  path?: string;
  category?: string | null;
  sort?: string | null;
};

export async function logSearch(input: SearchLogInput): Promise<void> {
  const h = await headers();
  const ua = h.get("user-agent") ?? "";

  const isPrefetch =
    h.get("purpose") === "prefetch" ||
    h.get("x-purpose") === "preview" ||
    (h.get("sec-purpose") ?? "").includes("prefetch");
  if (isPrefetch || isbot(ua)) return;

  const jar = await cookies();
  if (jar.get(OPTOUT_COOKIE)?.value === "1") return;
  const visitorId = jar.get(VISITOR_COOKIE)?.value;
  const sessionId = jar.get(SESSION_COOKIE)?.value;
  if (!visitorId || !UUID_RE.test(visitorId)) return;
  if (!sessionId || !UUID_RE.test(sessionId)) return;

  const scrubbed = scrubPII(input.query);
  const row: AnalyticsEventRow = {
    id: input.id,
    name: "search",
    occurred_at: new Date().toISOString(),
    visitor_id: visitorId,
    session_id: sessionId,
    path: input.path ?? null,
    locale: input.locale ?? null,
    device_type: deviceTypeFrom(ua),
    query_raw: scrubbed,
    query_norm: normalizeSearchTerm(scrubbed),
    result_count: input.resultCount,
    result_ids: input.resultIds.slice(0, 20),
    category: input.category ?? null,
    sort: input.sort ?? null,
  };

  const { error } = await analyticsTable("analytics_events").upsert([row], {
    onConflict: "id",
    ignoreDuplicates: true,
  });
  if (error) console.warn("[analytics] search log failed:", error.message);
}
